name: OrangeKillMessageReloaded
version: '${project.version}'
main: com.orangekillmessagereloaded.OrangeKillMessageReloaded
api-version: '1.20'
author: DuoDuoJuZi
website: https://github.com/DuoDuoJuZi/OrangeKillMessageReloaded
description: 自定义你的击杀消息，伤害性不大，侮辱性极强
commands:
  okm:
    description: Main command
    usage: /okm <help|set|reload>
    aliases: km
    children:
      help:
        description: Help command
        usage: /okm help
        permission: okm.help
      set:
        description: Set custom message
        usage: /okm set
        permission: okm.set
      reload:
        description: Reload plugin
        usage: /okm reload
        permission: okm.reload